#!/bin/bash


# disable CapsLock & map to Escape
#setxkbmap -option caps:swapescape

# clipboard synching
autocutsel -fork &
autocutsel -selection PRIMARY -fork &

xset +fp /usr/share/fonts/local
xset fp rehash

# set wallpaper
feh --bg-scale /home/sonny/Imgs/wallpaper

# ---- window manager ----
# launch dwm status bar
while true; do
  $HOME/Scripts/dwm_statusbar
  sleep 2
done &

# launch dwm
while true; do
    # Log stderror to a file
    #dwm 2>  $HOME/.logs/dwm.log
    # No error logging
    dwm >/dev/null
done
